all:
	g++ change.cpp -o change.out
	g++ fractional_knapsack.cpp -o fractional_knapsack.out
	g++ dot_product.cpp -o dot_product.out
	g++ covering_segments.cpp -o covering_segments.out
	g++ different_summands.cpp -o different_summands.out